/**
 * Root ESLint flat config (ESLint v9).
 *
 * Lints apps/ + packages/ together so the two React/TypeScript apps
 * (curation + browser) and the shared packages (ontology, heatmap)
 * stay on one rule set. Intentionally pragmatic: real-bug rules on,
 * stylistic-nit rules off. Run `npm run lint` from inside either
 * app's workspace or `npx eslint .` from repo root.
 *
 * Type-aware rules (`@typescript-eslint/no-floating-promises` etc.)
 * are NOT enabled — they require a project-aware parserOptions
 * passthrough that doubles lint time and trips on the monorepo's
 * tsconfig layout. Stick with the recommended (syntactic) ruleset
 * for now; add type-aware rules in a follow-up if real bugs slip
 * through.
 */

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

export default tseslint.config(
  // Global ignores. Build outputs + tooling-generated files + the
  // legacy GemBrow Vue source the React port replaces.
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.vite/**",
      "**/coverage/**",
      "**/*.d.ts",
      // Generated by `openapi-typescript` — don't lint vendor types.
      "apps/*/src/api/schema.ts",
    ],
  },
  // Recommended JS + TS rules across all TS/TSX files.
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      // ── React hooks ────────────────────────────────────────────
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // ── React Fast-Refresh safety ──────────────────────────────
      // Vite HMR breaks when a module exports both components and
      // non-component values. Warn (not error) so existing call
      // sites that mix exports surface as findings without
      // blocking lint.
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],

      // ── TypeScript tweaks ──────────────────────────────────────
      // Underscore-prefixed args are intentional throwaways (event
      // handlers, ignored callback params). Don't flag them.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // ``any`` is a legit escape hatch in glue code (JSON
      // round-trips, third-party APIs without types). Warn so it
      // surfaces in review without blocking.
      "@typescript-eslint/no-explicit-any": "warn",
      // We use ``// @ts-expect-error`` (with reason) liberally
      // when a downstream library type lags. Allow but require the
      // explanation.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": "allow-with-description",
          "ts-ignore": true,
          "ts-nocheck": true,
          "ts-check": false,
          minimumDescriptionLength: 3,
        },
      ],

      // ── Off / relaxed ──────────────────────────────────────────
      // Tailwind classNames + chained method calls run long; let
      // prettier handle wrapping.
      "max-len": "off",
      // Both apps use console.log for dev-time diagnostics that
      // ship behind a NODE_ENV check; we don't want lint shouting
      // every time.
      "no-console": "off",
      // ``Function`` / empty interface are flagged by default; we
      // use both intentionally (function-prop types, marker
      // interfaces). Drop to warn.
      "@typescript-eslint/no-empty-object-type": "warn",
      // ``no-prototype-builtins`` and friends from the JS
      // recommended set don't add signal in a modern TS codebase.
      "no-prototype-builtins": "off",
      // We sometimes rely on type-narrowing via `!` after explicit
      // guards. Trust the author here.
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  // Per-app overrides — anything app-specific lives in its own
  // block so the global rules stay neutral.
  {
    files: ["apps/curation/**/*.{ts,tsx}"],
    rules: {
      // Curation has a lot of intentional `any` in agent-stream
      // parsers (SSE payloads pre-snakeify); turn it down further
      // there. Real fixes will narrow these as the wire types
      // tighten.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  // Test files — relax a couple of rules.
  {
    files: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  // Vite / config / Node-context files. `**/scripts/**` covers the
  // stand-alone maintenance scripts each app keeps (contract probes,
  // fixture emitters) — they run under Node, not in a browser, so
  // `process` / `console` / `fetch` are all legitimately global.
  {
    files: [
      "**/vite.config.ts",
      "**/eslint.config.{js,ts}",
      "**/postcss.config.{js,cjs}",
      "**/tailwind.config.{js,ts}",
      "**/scripts/**/*.{js,mjs,cjs,ts}",
    ],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
);
